nami_admin_dashboard:
    path:     /
    methods:  [GET]
    defaults: { _controller: NamiAdminBundle:Default:index }

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
